### ISSUE TITLE
Policy - add more methods

### ISSUE THREAD

**Issue by aldarund** [MailRoute/mailroute_ruby#4]
enableSpamFiltering/disableSpamFilter - field bypass_spam_checks Y\N
enableVirusFiltering/disableVirusFilter - field bypass_virus_checks Y\N
enableBadHdrFilter/disableBadHdrFilter -field bypass_header_checks Y\N
enableBannedFilter/disableBannedFilter -field bypass_banned_checks Y\N
setAntiSpamMode(Modeenum.mode) - set field anti_spam_preset to "lenient","standard","aggressive"

**Comment by DNNX** [comment]
`enableSpamFiltering/disableSpamFilter` doesn't seem quite consistent. I'll make it `enableSpamFilter/disableSpamFilter`. Please let me know if I shouldn't for some reason.

Also, I don't think that `enableBadHdrFilter` is not very good name for a method. `Hdr` is not a word. Why don't we change it to `enableBadHeaderFilter` or even `enableHeaderFilter` (I would prefer the latter)?

**Comment by aldarund** [comment]
Ok, sounds goods for me.
