### ISSUE TITLE
EmailAccount::create() - parse input and split to domain and localpart

### ISSUE THREAD

**Issue by aldarund** [MailRoute/mailroute_ruby#7]
Should be able to add email account like create("test@doamin.com")

**Comment by DNNX** [comment]
`create_opt` field is required, and it has no default value, according to [the docs](https://mailroute.zendesk.com/entries/23190947-API-Part-5-Email-Account-Resource). What should be its value be set to?

**Comment by DNNX** [comment]
Nevermind, I found an answer. It's `"generate_pwd"` :)
